[theme]
base="light"
primaryColor="#10B981"              # Emerald green for buttons and highlights
backgroundColor="#FFFFFF"           # Clean white background
secondaryBackgroundColor="#F9FAFB"  # Subtle gray background
textColor="#111827"                 # Dark gray text
font="sans serif"
