[theme]
base="light"
primaryColor="#10B981"              # Emerald green (buttons, highlights)
backgroundColor="#FFFFFF"           # White background
secondaryBackgroundColor="#F9FAFB"  # Light gray background for contrast
textColor="#111827"                 # Dark gray (almost black) text
font="sans serif"
